export enum Endpoints {
	EightBall = '8ball',
	Cat = 'cat',
	Fact = 'fact',
	Image = 'img',
	Name = 'name',
	Owoify = 'owoify',
	Why = 'why',
}

export enum ImageCategory {
	Smug = 'smug',
	Woof = 'woof',
	Gasm = 'gasm',
	EightBall = '8ball',
	Goose = 'goose',
	Cuddle = 'cuddle',
	Avatar = 'avatar',
	Slap = 'slap',
	Pat = 'pat',
	Gecg = 'gecg',
	Feed = 'feed',
	FoxGirl = 'fox_girl',
	Lizard = 'lizard',
	Neko = 'neko',
	Hug = 'hug',
	Meow = 'meow',
	Kiss = 'kiss',
	Wallpaper = 'wallpaper',
	Tickle = 'tickle',
	Spank = 'spank',
	Waifu = 'waifu',
	Lewd = 'lewd',
	NekoGif = 'ngif',
}
